_commit: v0.2.0
_src_path: https://github.com/gabriel-andreescu/BethesdaModKit.git
author: GabonZ
bmk_repository: https://github.com/gabriel-andreescu/BethesdaModKit.git
components:
  - native
  - plugin_generation
description: Slows time when detected while sneaking in combat.
devbench_api: true
devbench_tests: true
game: skyrim
mcm: false
mutagen_source: src/mutagen/ShadowOpportunist
native_settings: true
native_source: src/native
pack_assets: false
pre_commit: true
project_name: ShadowOpportunist
