[General]

; Toggle debug logging
bDebugLogging = 0

; Toggle visuals and sound
bEnableEffectFeedback = 1

; Duration in seconds
iDuration = 3

; Keep the player at normal speed
bSlowTimePlayerImmunity = 1

; Required perks when the New Perk Addon is disabled: 0xFORMID~Plugin.esp,...
; Leave empty for no requirements
sRequiredPerks =
